version: 2.1
jobs:
  node:
    working_directory: ~/project
    docker:
      - image: cimg/node:18.10.0

    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: jest tests
          command: |
            mkdir -p test-results/jest
            yarn run test
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/junit.xml

      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

  android-build-and-deploy-to-app-distribution:
    working_directory: ~/project/android
    docker:
      - image: circleci/android:api-29-node
    steps:
      - checkout:
          path: ~/project

      - attach_workspace:
          at: ~/project

      - restore_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}

      - run: bundle install

      - save_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle

      - run:
          name: fastlane tests
          command: |
            mkdir -p test-results/fastlane
            bundle exec fastlane test
            mv fastlane/report.xml test-results/fastlane
      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

      - run:
          name: deploy to app distribution
          command: |
            bundle exec fastlane deliver_release_to_app_distribution
      - store_artifacts:
          path: app/build/outputs/apk/release/app-release.apk

workflows:
  node-android:
    jobs:
      - node
      - android-build-and-deploy-to-app-distribution:
          requires:
            - node
# VS Code Extension Version: 1.3.0
