source "https://rubygems.org"
ruby '3.0.2'

gem "fastlane"
gem "danger"
gem "dotenv"
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
