default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
    Dotenv.load ".env"
  end

  desc "create app"
  lane :create_app do
    produce
  end

  desc "clone certificates and provisioning profiles required"
  lane :setup_code_signing do
    match
  end

  lane :tests do
    run_tests(workspace: "ExplreFastLane.xcworkspace",
              scheme: "ExplreFastLane")
  end

  desc "upload ipa t appetize"
  lane :upload_to_appetize do
    app_path = File.join(__dir__, "ExplreFastLane.ipa")
    UI.message("App path: #{app_path}")
    UI.user_error!("Couldn't find app") unless app_path
    zipped_bundle = zip(path: app_path, output_path: File.join(__dir__, "Result.zip"))
    appetize(path: zipped_bundle)
    url = appetize_viewing_url_generator(scale: "75", color: "black")
    UI.message("Generated URL: #{url}")
  end

  desc "Build locally"
  lane :local_build do
    #setup_code_signing
    #gym
    #upload_to_appetize
  end
end
