default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
    Dotenv.load ".env"
  end

  desc "create app"
  lane :create_app do
    produce
  end

  desc "clone certificates and provisioning profiles required"
  lane :setup_code_signing do
    match
  end

  lane :tests do
    run_tests(workspace: "ExplreFastLane.xcworkspace",
              scheme: "ExplreFastLane")
  end

  desc "Build locally"
  lane :local_build do
    setup_code_signing
    gym
  end
end
