# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build"
  lane :build do |options|
    gradle(
      task: "clean assemble",
      flavor: options[:flavor],
      build_type: "Release"
    )
  end

  desc "Deliver to app distribution"
  lane :deliver_to_app_distribution do |options|
    firebase_app_distribution(
      app: options[:app],
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      groups: "testers",
    )
  end

  desc "Deliver Release to Firebase App Distribution"
  lane :build_and_deliver do |options|
    build(flavor: options[:flavor])
    deliver_to_app_distribution(app: options[:app])
  end

  desc "Deliver PROD Release to Firebase App Distribution"
  lane :prod_build_and_deliver do |options|
    build_and_deliver(flavor: "prod", app: ENV["ANDROID_PROD_APP_ID"])
  end

  desc "Deliver STAG Release to Firebase App Distribution"
  lane :stag_build_and_deliver do |options|
    build_and_deliver(flavor: "stag", app: ENV["ANDROID_STAG_APP_ID"])
  end

  desc "Deliver DEV Release to Firebase App Distribution"
  lane :dev_build_and_deliver do |options|
    build_and_deliver(flavor: "development", app: ENV["ANDROID_DEV_APP_ID"])
  end

  desc "Deliver ENV Release to Firebase App Distribution"
  lane :env_build_and_deliver do |options|
    case options[:env]
    when "prod"
      prod_build_and_deliver
    when "stag"
      stag_build_and_deliver
    when "dev"
      dev_build_and_deliver
    else
      UI.user_error!("env should be one of 'prod', 'stag', 'dev'")
    end
  end
end
